# Author: Dr. Konstantin Selyunin
# Created: 5 April 2020
# Version: v0.1
# Copyright (C) 2020 Redshift Labs Pty Ltd. All rights reserved

# Revision history:
# 2020.04.05:
#   creating pipeline for running pytest and generating header file
#   and uploading the header file to the bitbucket repo download section

# Summary: this is a configuration file for running the bitbucket pipelines.
# Whenever `git push` is happened, the bitbucket pipeline is initiated on the bitbucket cloud.
# The pipeline uses `python3` in the `rsl_xml_svd` docker image
# to run the tests, generate header file and upload header file to downloads section.

# Upon creating the pipeline, bitbucket performs the following steps:
# 1. Fist, bitbucket creates a container from the `rsl_xml_svd` docker image.
# This image is created based on the `Dockerfile` in this repository
# (with the steps defined in README.md), and contains the python3.7, pytest, and jinja2
# installed in the ubuntu image
# The container and image do NOT contain any sources.
# The container only has a build environment prepared for building the sources.
# 2. Second, bitbucket cloud copies the sources of the current commit
# to the created container.
# 3. bitbucket cloud then performs the pipelines steps defined in this file
# 4. it collects the artifacts and makes them available as a result of the pipeline
# 5. It destroys the containers and performs tear up steps.


image: kselyunin/rsl_xml_svd:v0.1

pipelines:
  default:
    - step:
        name: Running pytests
        script:
          - echo "running pytest"
          - pwd
          - ls
          - python3.7 -m pytest -m svd

